config/routes.rb
Rails.application.routes.draw do
  get 'article_comment/index'
  get 'article_comment/destroy'
  post 'article_comment/create'

  get 'article/index'
  post 'article/created'
  get "article/article_list_edit"
  get "article/delete_article"
  get "article/edit_article"
  post "article/edit_article_post"
  
  get 'users/index'
  get 'designer/index'

  root 'designer#index'
  get 'designer/blog'
  get 'designer/blog_list'

  delete '/logout' => 'users#destroy', as: :logout
  post 'users/logins'
  get 'users/logins'
  resources :users

end

app/controllers/designer_controller.rb
class DesignerController < ApplicationController
  def index
  	@article = Article.all.limit(100)
    @article_banner= Article.where(digest: "on").order(id: "desc")
    @article_banner_index=[]
    @article_banner.map{ |x|
      p !x['image_path'].blank?
        if !x['image_path'].blank?
              @article_banner_index << x       
        end
    }


  end

  def blog_list
  p  @article_list=params[:type]
    if @article_list=="ttxw"
          @article_category = "头条新闻"
    elsif   @article_list=="qdkf"  
          @article_category = "前端开发"
    elsif   @article_list=="zcgh"  
          @article_category = "职场规划"
    elsif   @article_list=="cxydsj"  
          @article_category = "程序猿的世界"
    elsif   @article_list=="sysj"  
          @article_category = "摄影世界"
    elsif   @article_list=="zptj"  
          @article_category = "作品推荐"
    elsif   @article_list=="tszt"  
          @article_category = "图书专题"
    elsif   @article_list=="sjzt"  
          @article_category = "设计专题"
    elsif   @article_list=="hysj"  
          @article_category = "环游世界"      
    end	

    @article_list_table = Article.where(category: @article_category).page(params[:page]||1).per_page(params[:per_page]||5).order(id:"desc")
    @article_comments3 = Article.all.limit(3)
    @article_comments6 = Article.all.limit(6)
  	# @categories=Fenlei.roots.page(params[:page]||1).per_page(params[:per_page]||10).order(id:"desc")
  end







  def blog
#查找评论
 @Articlecomment=Articlecomment.where(article_id: params[:id])
# 查找当前文章的信息
  @article = Article.find_by(id: params[:id].to_i)	
  #查找上一篇文章
 # if params[:id].to_i+1 >  Article.last.id
 # 	@article1_id=params[:id].to_i
 # else
 # 	@article1_id=params[:id].to_i+1
 # end

 # if params[:id].to_i-1 < Article.first.id
 # 	@article0_id=params[:id].to_i
 # else
 # 	@article0_id=params[:id].to_i-1
 # end
#获取所有数组ｉｄ的索引
  @article_all_id_arry=[]
  @article_all_id=Article.all
  @article_all_id.map{|x|  @article_all_id_arry<<x['id']  }
  p @article_all_id_arry
  p@article_in_arry_index = @article_all_id_arry.index( params[:id].to_i)



#  @article_next = params[:id].to_i+1
#  @article_last = params[:id].to_i-1
# # p !@article_all_id_arry.include?(@article_next)
#  while  !@article_all_id_arry.include?(@article_next)

#   if @article_next >  Article.last.id
#   @article_next=Article.last.id
#  else
#   p@article_next
#   @article_next=@article_next + 1
#  end

#  end 
#   while  !@article_all_id_arry.include?(@article_last)
#     if @article_last<  Article.first.id
#   @article_last=Article.last.id
#  else
#   p@article_last
#   @article_last=@article_next - 1
#  end
#  end 

p @article_all_id_arry.length-1
if @article_in_arry_index==@article_all_id_arry.length-1
   @article_in_arry_indexfirst = 0
else
   @article_in_arry_indexfirst = @article_in_arry_index+1
end



  @article1 = Article.where(id:@article_all_id_arry[@article_in_arry_indexfirst])[0]
  @article0 = Article.where(id: @article_all_id_arry[@article_in_arry_index-1])[0]		
  end









# def create_article
  
# end


# def method_name
  
# end






































end

app/helpers/designer_helper.rb
module DesignerHelper
end

app/views/designer/_footer.html.erb
<footer class="row" id="footer">
    <div class="container">
        <div class="row top-footer">
            <div class="widget col-sm-3 widget-about">
                <div class="row m0"><a href="index.html"><img src="/index1949/images/logo-black-green.png" alt=""></a></div>
            </div>
            <div class="widget col-sm-5 widget-menu">
                <div class="row">
                     <ul class="nav column-menu white-bg">
                       <li><a href="/designer/blog_list?type=ttxw">头条新闻<span class="pull-right"></span></a></li>
                                <li class=""><a href="/designer/blog_list?type=qdkf"　>前端开发<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=zcgh">职场规划<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=cxydsj">程序猿的世界<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=sysj">摄影世界<span class="pull-right"></span></a></li>
                    </ul>
                    <ul class="nav column-menu white-bg">
                         <li><a href="/designer/blog_list?type=zptj">作品推荐<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=tszt">图书专题<span class="pull-right"></span></a></li>
                                 <li><a href="/designer/blog_list?type=hysj">环游世界<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=sjzt">设计专题<span class="pull-right"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-sm-4 widget-subscribe">
                <h5 class="widget-title">subscribe to our newsletter.</h5>
                <form action="#" method="post" class="form-inline subscribe-form">                    
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                </form>
            </div>
        </div>
       
    </div>
</footer>

app/views/designer/_header.html.erb
<header class="row transparent white" data-spy="affix" data-offset-top="300" id="header">
    <div class="container">
        <div class="row top-header">
            <div class="col-sm-4 search-form-col">
              <!--   <form action="#" method="get" class="search-form">
                    <div class="input-group">
                        <span class="input-group-addon"><img src="/index1949/images/search-icon-dark.png" alt=""></span>
                        <input type="search" class="form-control" placeholder="search">
                    </div>
                </form> -->
            </div>
            <div class="col-sm-4 logo-col text-center">
                <a href="/designer/index"><img src="/index1949/images/logo-black-green.png" alt=""></a>
            </div>
            <div class="col-sm-4 menu-trigger-col">
                <button class="menu-trigger black pull-right">
                    <span class="active-page">Blog Details</span>
                    <img src="/index1949/images/menu-align-dark.png" alt="" class="icon-burger">
                    <img src="/index1949/images/menu-close-dark.png" alt="" class="icon-cross">
                </button>
            </div>
        </div>        
    </div>
    <div class="row menu-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 menu-col">
                    <div class="row">
                        <ul class="nav column-menu white-bg">
                           <li><a href="/designer/blog_list?type=ttxw">头条新闻<span class="pull-right"></span></a></li>
                                <li class=""><a href="/designer/blog_list?type=qdkf"　>前端开发<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=zcgh">职场规划<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=cxydsj">程序猿的世界<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=sysj">摄影世界<span class="pull-right"></span></a></li>
                              
                        </ul>
                        <ul class="nav column-menu white-bg">
                             <li><a href="/designer/blog_list?type=zptj">作品推荐<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=tszt">图书专题<span class="pull-right"></span></a></li>
                                 <li><a href="/designer/blog_list?type=hysj">环游世界<span class="pull-right"></span></a></li>
                                <li><a href="/designer/blog_list?type=sjzt">设计专题<span class="pull-right"></span></a></li>
                        </ul>
                    </div>
                </div>
 <div class="col-md-4 sidebar">    
   <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <div class="author-avatar row"><a href="#"><img style="width: 120px; height: 120px;" src="/uploads/TIM图片20171204233824.png" alt="" class="img-circle"></a></div>
                        <a href="#"><h2 class="author-name">
                             <%if logged_in?%>
                            <%=current_user.email%>
                            <%else%>
                            未登陆
                            <%end%> 
                            </h2></a>
                        
                        <p>种一棵树最好的时间是十年前，其次是现在。</p>
                         <%= link_to "注销账号", logout_path, method: :delete,:class=>"know-more" %>
                    </div>
                    <ul class="nav social-nav">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </aside>
</div>











         <!--        <div class="col-sm-4 subscribe-col">
                    <h5 class="widget-title">subscribe to our newsletter.</h5>
                    <form action="#" method="post" class="form-inline subscribe-form">                    
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email">
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                    </form>
                    <ul class="nav social-nav white">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div> -->
            </div>
        </div>
    </div>
</header>

app/views/designer/blog.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Chivalric</title>


<link rel="stylesheet" href="/index1949/css/bootstrap.min.css">
<link rel="stylesheet" href="/index1949/css/font-awesome.min.css">
<link rel="stylesheet" href="/index1949/vendors/owl-carousel/assets/owl.carousel.css">
<link rel="stylesheet" href="/index1949/vendors/magnific-popup/magnific-popup.css">
<link rel="stylesheet" href="/index1949/vendors/flexslider/flexslider.css">

<link href="/index1949/css/style.css" rel="stylesheet">
<link href="/index1949/css/theme/green.css" rel="stylesheet">


</head>
<body class="home">

<%=render 'header'%>

<section class="row content-wrap">
    <div class="container">
        <div class="row">
            <div class="col-md-9 single-post-contents" >
                <article class="single-post-content row m0 post" >
                    <header class="row">                        
                        <h5 class="post-meta">
                            <a href="#" class="date"><%= @article.postedtime %></a>
                            <span class="post-author"><i>by</i><a href="#"><%= @article.inputer %></a></span>
                        </h5>
                        <h2 class="post-title"><%= @article.title %></h2>
                        <div class="row">
                            <h5 class="taxonomy pull-left"><i>in</i> <a href="#"><%= @article.category %></a></h5>
                            <div class="response-count pull-right"><img src="/index1949/images/comment-icon-gray.png" alt=""><%= @Articlecomment.length %></div>
                        </div>
                    </header>
                    <div class="featured-content row m0">
                        <a href="#"><img src="/uploads/<%=@article.image_path%>" alt=""></a>
                    </div>


                    <div class="post-content row" style="overflow: hidden;">
                   
                  
                    <%= sanitize  @article.details  %>




                        <br>
                        <!-- 16:9 aspect ratio -->
                     
                        <br>
                        
                        <!-- Place somewhere in the <body> of your page -->
                        <div class="thumbCarousel row m0">
                            <div id="slider" class="flexslider">
                                <ul class="slides">
                                    <li><img src="/index1949/images/posts/gallery/1.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/2.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/3.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/4.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/1.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/2.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/3.jpg" alt=""></li>
                                </ul>
                            </div>
                            <div id="carousel" class="flexslider">
                                <ul class="slides">
                                    <li><img src="/index1949/images/posts/gallery/s1.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/s2.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/s3.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/s4.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/s1.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/s2.jpg" alt=""></li>
                                    <li><img src="/index1949/images/posts/gallery/s3.jpg" alt=""></li>
                                </ul>
                            </div>
                        </div>
                        <br>
                       <!--  <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> -->
                    </div>
                    <div class="row m0 tags">
                        <a href="#" class="tag">music</a>
                        <a href="#" class="tag">tegs</a>
                        <a href="#" class="tag">tegs hover</a>
                    </div>
                    
                    <ul class="pager">
                        <li>
                            <h4>上一页</h4>
                            <h2 class="post-title"><a href="/designer/blog?id=<%=@article0.id%>">  <%=@article0.title%> </a></h2>
                            <h5 class="taxonomy pull-left"><i>in</i> <a href="#"> <%=@article0.category%> </a></h5>
                        </li>
                        <li>
                            <h4>下一页</h4>
                            <h2 class="post-title"><a href="/designer/blog?id=<%=@article1.id%>"><%=@article1.title%> </a></h2>
                            <h5 class="taxonomy pull-left"><i>in</i> <a href="#"> <%=@article1.category%> </a></h5>
                        </li>
                    </ul>
                    
                    <div class="row m0 comments">
                        <h5 class="response-count">
                           <a href="#comment-form" class="btn btn-primary pull-right">
                                <span>回复一下</span></a></h5>
                        <!--Comments-->
                        <div class="media comment">
                            <!-- <div class="media-left">
                                <a href="#"><img src="/index1949/images/posts/c1.jpg" alt="" class="img-circle"></a>
                            </div> -->

                       <!--      
                            <div class="media-body">
                                <h4><a href="#">Mark Sanders</a></h4>
                                <h5><a href="#" class="date">feb 17, 2016 at 3:30pm</a> | <a href="#" class="reply-link">reply</a></h5>
                                <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>                                
                                






                                <div class="media comment reply">
                                    <div class="media-left">
                                        <a href="#"><img src="/index1949/images/posts/c2.jpg" alt="" class="img-circle"></a>
                                    </div>
                                    <div class="media-body">
                                        <h4><a href="#">Mark Sanders</a></h4>
                                        <h5><a href="#" class="date">feb 17, 2016 at 3:30pm</a> | <a href="#" class="reply-link">reply</a></h5>
                                        <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
                                   
                                    </div>
                                </div>
                            </div> -->
                                                
                        <!--Comments-->


                    <% @Articlecomment.each do |e| %>
                        <div class="media comment">
                            <div class="media-left">
                                <a href="#"><img src="/uploads/5d11929c9154c42cb24fd918c460b5ed.jpg" alt="" class="img-circle"></a>
                            </div>
                            <div class="media-body">
                                <%if e.user_id==1000000000%>
                                <h4><a href="#">陌生人</a></h4>
                                <%else%>
                                <h4><a href="#"><%=User.find_by(id: e['user_id']).email%></a></h4>
                                <%end%>
                                <h5><a href="#" class="date"><%= e['comment_time']%></a> </h5>
                                <p><%= e['comment_text']%></p>
                            </div>
                        </div>
                   <%end%>



                    </div>
                    </div>
                 
                        <%= form_tag article_comment_create_path(id:@article.id),method: :post do%>
                        <!-- <h5 class="form-title"></h5> -->
                    
                    
                        <div class="form-group col-sm-12">
                            <!-- <h4 for="message">回复</h4> -->
                            <textarea name="message" id="message" class="form-control" placeholder="" maxlength="300"></textarea>
                        </div>
                        <div class="col-sm-12" style="margin-bottom: 50px;">
                            <button type="submit" class="btn-primary"><span>发送</span></button>
                            
                        </div>
                    <%end%>
                </article>
            </div>
            <div class="col-md-3 sidebar">               
                <!--Author Widget-->
             
                <!--Twitter Widget-->
                <aside class="row m0 widget widget-twitter" style="margin-top: 15px;">
                    <div class="widget-twitter-inner">
                        <h5 class="widget-meta"><i class="fa fa-twitter"></i>Twitter feed <a href="http://twitter.com/chivalricblog"></a></h5>
                        <div class="row tweet-texts">
                            <p><a href=""></a> <a href=""></a></p>
                        </div>
                        <div class="row timepast"></div>
                    </div>
                </aside>
                <!--Instagram Widget-->
                <aside class="row m0 widget widget-instagram">
                    <div class="widget-instagram-inner">
                        <h5 class="widget-meta"><i class="fa fa-twitter"></i>instagram feed <a href="http://twitter.com/chivalricblog"></a></h5>
                        <div id="instafeed"></div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>

<!--Footer-->
<%=render "footer"%>

<!--========== jQuery (necessary for Bootstrap's JavaScript plugins) ==========-->
<script src="/index1949/js/jquery-2.2.0.min.js"></script>
<script src="/index1949/js/bootstrap.min.js"></script>
<script src="/index1949/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="/index1949/vendors/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="/index1949/vendors/instafeed/instafeed.min.js"></script>
<script src="/index1949/vendors/imagesLoaded/imagesloaded.pkgd.min.js"></script>
<script src="/index1949/vendors/isotope/isotope.pkgd.min.js"></script>
<script src="/index1949/vendors/flexslider/jquery.flexslider-min.js"></script>
<script src="/index1949/js/theme.js"></script>
</body>
</html>